// Generated by the PersonaOn pipeline from https://personaon.com
// Edit via the builder agent (vibe-coding) or directly. One file = one site.
export const site = {
  "identity": {
    "name": "PersonaOn",
    "handle": "personaon",
    "archetype": "company",
    "headline": "your portfolio, but it answers.",
    "links": [
      {
        "label": "personaon.com",
        "href": "https://personaon.com"
      }
    ]
  },
  "seo": {
    "description": "PersonaOn transforms your resume into a dynamic page that answers questions, books meetings, and captures interest automatically.",
    "ogImage": "/gen/personaon-proj0.png"
  },
  "knowsAbout": [
    "Free",
    "No credit card",
    "Live in 3 minutes",
    "Your resume",
    "Calendar booking",
    "Dashboard insights"
  ],
  "brand": {
    "colors": {
      "primary": "#0066CC",
      "secondary": "#E0A21A",
      "accent": "#2BB673",
      "background": "#F5F5F7",
      "textPrimary": "#1D1D1F"
    },
    "fonts": {
      "display": "Instrument Serif",
      "body": "Geist",
      "mono": "JetBrains Mono"
    }
  },
  "page": [
    {
      "type": "Hero",
      "props": {
        "eyebrow": "Product · Living Portfolio",
        "headline": "Your portfolio, but it answers.",
        "headlineAccent": "While you sleep",
        "lede": "PersonaOn transforms your resume into a dynamic page that answers questions, books meetings, and captures interest automatically.",
        "ctaPrimary": {
          "label": "Start a conversation →",
          "href": "#ask"
        },
        "ctaSecondary": {
          "label": "See the work",
          "href": "#work"
        },
        "meta": [
          "personaon.com"
        ],
        "chat": {
          "greeting": "PersonaOn's representative",
          "suggestedQuestions": [
            "What can a portfolio that answers do?",
            "How is PersonaOn different from LinkedIn?",
            "How does it use my resume?",
            "Is it really my voice, not AI?"
          ],
          "placeholder": "Ask me anything…"
        }
      }
    },
    {
      "type": "ProofStrip",
      "props": {
        "items": [
          "Free",
          "No credit card",
          "Live in 3 minutes",
          "Your resume",
          "Calendar booking",
          "Dashboard insights"
        ]
      }
    },
    {
      "type": "AskAbout",
      "props": {
        "kicker": "Ask me about",
        "title": "What visitors most want to know.",
        "blurb": "Every question is a real conversation, answered in their voice.",
        "topics": [
          "What can a portfolio that answers do?",
          "How is this different from a website builder?",
          "How is my page built from my resume?",
          "Who is PersonaOn for?",
          "Is PersonaOn really free?",
          "How does it book meetings?"
        ]
      }
    },
    {
      "type": "ProjectShowcase",
      "props": {
        "kicker": "Selected work",
        "title": "What they have built.",
        "blurb": "Ask the representative for the story behind any of these.",
        "projects": [
          {
            "title": "Transform Your Resume",
            "body": "Turn your static PDF into a dynamic page that speaks for you, sourced from your material.",
            "tags": [
              "PDF",
              "Dynamic",
              "Voice"
            ],
            "media": {
              "src": "/gen/personaon-proj0.png",
              "alt": "Transform Your Resume"
            }
          },
          {
            "title": "Automate Lead Qualification",
            "body": "Your page answers common questions from prospects and books meetings into your calendar automatically.",
            "tags": [
              "Leads",
              "Meetings",
              "Efficiency"
            ],
            "media": {
              "src": "/gen/personaon-proj1.png",
              "alt": "Automate Lead Qualification"
            }
          },
          {
            "title": "Understand Visitor Interest",
            "body": "Get a dashboard view of every question asked and who interacted with your living portfolio.",
            "tags": [
              "Analytics",
              "Insights",
              "Engagement"
            ],
            "media": {
              "src": "/gen/personaon-proj2.png",
              "alt": "Understand Visitor Interest"
            }
          }
        ]
      }
    },
    {
      "type": "Faq",
      "props": {}
    },
    {
      "type": "PullQuote",
      "props": {
        "quote": "Your work speaks. Your resume doesn't.",
        "accentWord": "speaks",
        "cite": "— PersonaOn"
      }
    },
    {
      "type": "OpportunityCapture",
      "props": {
        "kicker": "Lead capture",
        "title": "Get Your Living Portfolio",
        "body": "Create your personalized page in minutes, answering questions and booking meetings for you.",
        "submitLabel": "Start Free Now"
      }
    },
    {
      "type": "Footer",
      "props": {
        "wordmark": "Built on PersonaOn",
        "tagline": "A living persona. It answers, captures, and gets smarter the more it is used.",
        "links": [
          {
            "label": "Ask",
            "href": "#ask"
          },
          {
            "label": "Work",
            "href": "#work"
          },
          {
            "label": "FAQ",
            "href": "#faq"
          },
          {
            "label": "personaon.com",
            "href": "https://personaon.com"
          }
        ]
      }
    }
  ],
  "faq": [
    {
      "q": "What can a portfolio that answers do?",
      "a": "A PersonaOn page answers visitor questions about your work, books meetings into your calendar, and captures interest while you sleep."
    },
    {
      "q": "How is PersonaOn different from LinkedIn?",
      "a": "Unlike LinkedIn, your PersonaOn page actively answers specific questions in your voice, providing context and booking direct calls."
    },
    {
      "q": "How does it use my resume?",
      "a": "We build your page by assembling content directly from your resume or LinkedIn PDF export, ensuring accuracy and your unique story."
    },
    {
      "q": "Is it really my voice, not AI?",
      "a": "Yes, every word traces back to your material or edits you made; it's your real voice, never synthetic or hallucinated."
    }
  ],
  "previewExchanges": [
    {
      "q": "What can a portfolio that answers do?",
      "a": "A PersonaOn page answers visitor questions about your work, books meetings into your calendar, and captures interest while you sleep."
    },
    {
      "q": "How is PersonaOn different from LinkedIn?",
      "a": "Unlike LinkedIn, your PersonaOn page actively answers specific questions in your voice, providing context and booking direct calls."
    },
    {
      "q": "How does it use my resume?",
      "a": "We build your page by assembling content directly from your resume or LinkedIn PDF export, ensuring accuracy and your unique story."
    },
    {
      "q": "Is it really my voice, not AI?",
      "a": "Yes, every word traces back to your material or edits you made; it's your real voice, never synthetic or hallucinated."
    }
  ]
};
